fragment StoriesParts on Stories {
  __typename
  title
  date
  scripture
  scriptureText
  featuredQuote
  hashtags
  audioUrl
  topics
  excerpt
  author
  heroImage
  tags
  seoTitle
  seoDescription
  featuredImage
  metaTitle
  metaDescription
  ogImage
  hebrew_scripture
  christian_scripture
  themes
  summary
  body
}
