fragment StoriesParts on Stories {
  __typename
  title
  seoTitle
  seoDescription
  featuredImage
  metaTitle
  metaDescription
  ogImage
  author
  date
  hebrew_scripture
  christian_scripture
  themes
  summary
  body
}
